# Image processing with PIL

In [1]:
from PIL import Image
import numpy as np

image = Image.open('../data/frame/000001.png')
print(image.mode)

RGB


In [4]:
type(image)

PIL.PngImagePlugin.PngImageFile

In [5]:
array = np.array(image)
array.shape

(720, 1280, 3)

In [11]:
resize = image.resize((448,224))
resize.save('resize.png')

In [12]:
np.array(resize).shape

(224, 448, 3)

In [20]:
norm = array/255
print(norm.mean())

0.37346255872140455


In [23]:
img = np.array(resize)/255
mean_sum = np.array([0,0,0])
mean = np.array([img[:,:,0].mean(), img[:,:,1].mean(), img[:,:,2].mean()])
mean_sum = mean_sum + mean
mean_sum

array([0.38784404, 0.37597805, 0.35730355])

In [29]:
a = np.array([1,2,3])
b=np.array([3,2,1])
print("%s" % (a+b)**2)

[16 16 16]


In [37]:
img[:,:,0]

array([[0.56470588, 0.53333333, 0.53333333, ..., 0.39215686, 0.38823529,
        0.38431373],
       [0.55686275, 0.52941176, 0.54117647, ..., 0.38823529, 0.39215686,
        0.39607843],
       [0.57254902, 0.56078431, 0.55686275, ..., 0.39215686, 0.38823529,
        0.39215686],
       ...,
       [0.25490196, 0.23137255, 0.25098039, ..., 0.22352941, 0.21176471,
        0.21568627],
       [0.27058824, 0.23921569, 0.23921569, ..., 0.22352941, 0.23137255,
        0.21568627],
       [0.29803922, 0.2627451 , 0.23137255, ..., 0.23529412, 0.23137255,
        0.23529412]])

# Calculate the mean & std of frame data

In [2]:
import os 
from tqdm import tqdm

frame_dir = '..\\data\\frame'
frames = os.listdir(frame_dir)
frames = [os.path.join(frame_dir, i) for i in frames]

mean_sum = np.array([0,0,0])

for index in tqdm(range(len(frames))):
    img = Image.open(frames[index])
    img = img.resize((448,224))
    img = np.array(img)/255
    mean = np.array([img[:,:,0].mean(), img[:,:,1].mean(), img[:,:,2].mean()])
    mean_sum = mean_sum + mean

total_mean = mean_sum/len(frames)
print("Mean: %s" % total_mean)

diff_sum = np.array([0,0,0])
for index in tqdm(range(len(frames))):
    img = Image.open(frames[index])
    img = img.resize((448,224))
    img = np.array(img)/255
    for x in range(img.shape[0]):
        for y in range(img.shape[1]):
            diff = (img[x,y,:]-total_mean)**2
            diff_sum = diff_sum + diff
iff_sumnp.sqrt(/(len(frames)*img.shape[0]*img.shape[1])
print(")Std: %s" % std)

100%|██████████| 1871/1871 [01:34<00:00, 19.74it/s]
Mean: [0.41820913 0.35141712 0.31842441]
100%|██████████| 1871/1871 [11:47<00:00,  2.78it/s]
Std: [0.07000807 0.04945439 0.05429836]


In [3]:
np.sqrt(std)

array([0.26459038, 0.22238343, 0.23302009])

In [4]:
std

array([0.07000807, 0.04945439, 0.05429836])